openapi: 3.0.0
info:
  title: WaterBallSA Curriculums API
  version: 1.0.0
  description: |
    WaterBallSA 線上學習平台 - 課程 (Curriculum) API 規格

    **認證說明**：所有端點為公開 API，不需要認證
    **分頁說明**：使用 Spring Data 分頁機制，預設每頁 10 筆資料
    **排序說明**：預設按建立時間降序排列（createdAt,desc）

servers:
  - url: http://localhost:8081/api
    description: 開發環境
  - url: https://api.waterballsa.com/api
    description: 正式環境

paths:
  /curriculums:
    get:
      summary: 取得課程列表（分頁）
      description: 取得所有已發布的課程，支援分頁和排序
      operationId: getAllCurriculums
      tags:
        - Curriculums
      parameters:
        - name: page
          in: query
          description: 頁碼（從 0 開始）
          required: false
          schema:
            type: integer
            default: 0
            minimum: 0
          example: 0
        - name: size
          in: query
          description: 每頁筆數
          required: false
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 100
          example: 10
        - name: sort
          in: query
          description: 排序方式（格式：欄位名,方向）
          required: false
          schema:
            type: string
            default: "createdAt,desc"
          example: "createdAt,desc"
      responses:
        "200":
          description: 成功取得課程列表
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedCurriculumResponse'

  /curriculums/{id}:
    get:
      summary: 取得課程詳情
      description: 根據 ID 取得課程詳情（包含章節資訊）
      operationId: getCurriculumById
      tags:
        - Curriculums
      parameters:
        - name: id
          in: path
          description: 課程 ID
          required: true
          schema:
            type: integer
          example: 1
      responses:
        "200":
          description: 成功取得課程詳情
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Curriculum'
        "404":
          description: 找不到該課程
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                timestamp: "2025-12-08T10:30:00Z"
                status: 404
                error: "Not Found"
                message: "Curriculum not found with id: 1"
                path: "/api/curriculums/1"

  /curriculums/search:
    get:
      summary: 搜尋課程
      description: 根據課程標題或描述搜尋課程
      operationId: searchCurriculums
      tags:
        - Curriculums
      parameters:
        - name: q
          in: query
          description: 搜尋關鍵字
          required: true
          schema:
            type: string
          example: "Java"
        - name: page
          in: query
          description: 頁碼（從 0 開始）
          required: false
          schema:
            type: integer
            default: 0
          example: 0
        - name: size
          in: query
          description: 每頁筆數
          required: false
          schema:
            type: integer
            default: 10
          example: 10
        - name: sort
          in: query
          description: 排序方式
          required: false
          schema:
            type: string
            default: "createdAt,desc"
          example: "createdAt,desc"
      responses:
        "200":
          description: 成功取得搜尋結果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedCurriculumResponse'

  /curriculums/difficulty/{level}:
    get:
      summary: 根據難度篩選課程
      description: 取得指定難度的所有課程
      operationId: getCurriculumsByDifficulty
      tags:
        - Curriculums
      parameters:
        - name: level
          in: path
          description: 難度等級
          required: true
          schema:
            type: string
            enum:
              - BEGINNER
              - INTERMEDIATE
              - ADVANCED
          example: "BEGINNER"
        - name: page
          in: query
          description: 頁碼（從 0 開始）
          required: false
          schema:
            type: integer
            default: 0
          example: 0
        - name: size
          in: query
          description: 每頁筆數
          required: false
          schema:
            type: integer
            default: 10
          example: 10
        - name: sort
          in: query
          description: 排序方式
          required: false
          schema:
            type: string
            default: "createdAt,desc"
          example: "createdAt,desc"
      responses:
        "200":
          description: 成功取得指定難度的課程列表
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedCurriculumResponse'

  /curriculums/free:
    get:
      summary: 取得免費課程
      description: 取得所有免費課程（價格為 0）
      operationId: getFreeCurriculums
      tags:
        - Curriculums
      parameters:
        - name: page
          in: query
          description: 頁碼（從 0 開始）
          required: false
          schema:
            type: integer
            default: 0
          example: 0
        - name: size
          in: query
          description: 每頁筆數
          required: false
          schema:
            type: integer
            default: 10
          example: 10
        - name: sort
          in: query
          description: 排序方式
          required: false
          schema:
            type: string
            default: "createdAt,desc"
          example: "createdAt,desc"
      responses:
        "200":
          description: 成功取得免費課程列表
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedCurriculumResponse'

components:
  schemas:
    Curriculum:
      type: object
      required:
        - id
        - title
        - description
        - instructorName
        - price
        - currency
        - difficultyLevel
        - estimatedDurationHours
        - isPublished
        - createdAt
        - chapters
      properties:
        id:
          type: integer
          description: 課程 ID
          example: 1
        title:
          type: string
          description: 課程標題
          example: "完整 Java 開發入門課程"
        description:
          type: string
          description: 課程描述
          example: "從零開始學習 Java 程式設計，涵蓋基礎語法、OOP 概念及實戰專案"
        thumbnailUrl:
          type: string
          format: uri
          description: 課程縮圖 URL（可選）
          example: "https://example.com/thumbnails/java-course.jpg"
        instructorName:
          type: string
          description: 講師姓名
          example: "張老師"
        price:
          type: number
          format: double
          description: 課程價格
          example: 1990.00
        currency:
          type: string
          description: 幣別
          example: "TWD"
        difficultyLevel:
          type: string
          enum:
            - BEGINNER
            - INTERMEDIATE
            - ADVANCED
          description: 難度等級
          example: "BEGINNER"
        estimatedDurationHours:
          type: integer
          description: 預估總時長（小時）
          example: 40
        isPublished:
          type: boolean
          description: 是否已發布
          example: true
        publishedAt:
          type: string
          format: date-time
          description: 發布時間（可選）
          example: "2025-01-01T00:00:00Z"
        createdAt:
          type: string
          format: date-time
          description: 建立時間
          example: "2024-12-01T00:00:00Z"
        chapters:
          type: array
          description: 章節列表
          items:
            $ref: '#/components/schemas/ChapterSummary'

    ChapterSummary:
      type: object
      description: 章節摘要資訊（不包含課程內容）
      required:
        - id
        - curriculumId
        - title
        - orderIndex
        - createdAt
      properties:
        id:
          type: integer
          description: 章節 ID
          example: 1
        curriculumId:
          type: integer
          description: 所屬課程 ID
          example: 1
        title:
          type: string
          description: 章節標題
          example: "Java 基礎語法"
        description:
          type: string
          description: 章節描述（可選）
          example: "學習 Java 變數、資料型別、流程控制等基礎語法"
        orderIndex:
          type: integer
          description: 排序索引
          example: 1
        createdAt:
          type: string
          format: date-time
          description: 建立時間
          example: "2024-12-01T00:00:00Z"

    PaginatedCurriculumResponse:
      type: object
      required:
        - content
        - pageable
        - totalPages
        - totalElements
        - last
        - size
        - number
        - first
        - numberOfElements
        - empty
      properties:
        content:
          type: array
          description: 課程列表
          items:
            $ref: '#/components/schemas/Curriculum'
        pageable:
          type: object
          description: 分頁資訊
          properties:
            pageNumber:
              type: integer
              example: 0
            pageSize:
              type: integer
              example: 10
            offset:
              type: integer
              example: 0
            paged:
              type: boolean
              example: true
            unpaged:
              type: boolean
              example: false
            sort:
              type: object
              properties:
                empty:
                  type: boolean
                  example: false
                sorted:
                  type: boolean
                  example: true
                unsorted:
                  type: boolean
                  example: false
        totalPages:
          type: integer
          description: 總頁數
          example: 5
        totalElements:
          type: integer
          description: 總筆數
          example: 42
        last:
          type: boolean
          description: 是否為最後一頁
          example: false
        size:
          type: integer
          description: 每頁筆數
          example: 10
        number:
          type: integer
          description: 當前頁碼
          example: 0
        sort:
          type: object
          properties:
            empty:
              type: boolean
              example: false
            sorted:
              type: boolean
              example: true
            unsorted:
              type: boolean
              example: false
        first:
          type: boolean
          description: 是否為第一頁
          example: true
        numberOfElements:
          type: integer
          description: 當前頁實際筆數
          example: 10
        empty:
          type: boolean
          description: 是否為空
          example: false

    ErrorResponse:
      type: object
      required:
        - timestamp
        - status
        - error
        - message
        - path
      properties:
        timestamp:
          type: string
          format: date-time
          description: 錯誤發生時間
          example: "2025-12-08T10:30:00Z"
        status:
          type: integer
          description: HTTP 狀態碼
          example: 404
        error:
          type: string
          description: 錯誤類型
          example: "Not Found"
        message:
          type: string
          description: 錯誤訊息
          example: "Resource not found"
        path:
          type: string
          description: 請求路徑
          example: "/api/curriculums/999"
