openapi: 3.0.0
info:
  title: WaterBallSA Lessons API
  version: 1.0.0
  description: |
    WaterBallSA 線上學習平台 - 課程 (Lesson) API 規格

    **認證說明**：所有端點為公開 API，不需要認證（Phase 1）
    **課程類型**：VIDEO（影片）、ARTICLE（文章）、SURVEY（測驗）
    **內容元資料**：使用 JSONB 欄位儲存不同類型課程的額外資訊

servers:
  - url: http://localhost:8081/api
    description: 開發環境
  - url: https://api.waterballsa.com/api
    description: 正式環境

paths:
  /lessons/{id}:
    get:
      summary: 取得課程詳情
      description: 根據 ID 取得課程詳情
      operationId: getLessonById
      tags:
        - Lessons
      parameters:
        - name: id
          in: path
          description: 課程 ID
          required: true
          schema:
            type: integer
          example: 1
      responses:
        "200":
          description: 成功取得課程詳情
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lesson'
        "404":
          description: 找不到該課程
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                timestamp: "2025-12-08T10:30:00Z"
                status: 404
                error: "Not Found"
                message: "Lesson not found with id: 1"
                path: "/api/lessons/1"

  /lessons/chapter/{chapterId}:
    get:
      summary: 取得章節的所有課程
      description: 根據章節 ID 取得該章節的所有課程
      operationId: getLessonsByChapterId
      tags:
        - Lessons
      parameters:
        - name: chapterId
          in: path
          description: 章節 ID
          required: true
          schema:
            type: integer
          example: 1
      responses:
        "200":
          description: 成功取得課程列表
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Lesson'
        "404":
          description: 找不到該章節
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /lessons/curriculum/{curriculumId}/free-preview:
    get:
      summary: 取得課程的免費試看課程
      description: 取得指定課程中所有標記為免費試看的課程
      operationId: getFreePreviewLessons
      tags:
        - Lessons
      parameters:
        - name: curriculumId
          in: path
          description: 課程 ID
          required: true
          schema:
            type: integer
          example: 1
      responses:
        "200":
          description: 成功取得免費試看課程列表
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Lesson'
        "404":
          description: 找不到該課程
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Lesson:
      type: object
      required:
        - id
        - chapterId
        - title
        - lessonType
        - contentMetadata
        - orderIndex
        - createdAt
      properties:
        id:
          type: integer
          description: 課程 ID
          example: 1
        chapterId:
          type: integer
          description: 所屬章節 ID
          example: 1
        title:
          type: string
          description: 課程標題
          example: "變數與資料型別"
        description:
          type: string
          description: 課程描述（可選）
          example: "介紹 Java 的基本資料型別和變數宣告方式"
        lessonType:
          type: string
          enum:
            - VIDEO
            - ARTICLE
            - SURVEY
          description: 課程類型
          example: "VIDEO"
        contentUrl:
          type: string
          format: uri
          description: 課程內容 URL（可選）
          example: "https://www.youtube.com/watch?v=abc123"
        contentMetadata:
          oneOf:
            - $ref: '#/components/schemas/VideoMetadata'
            - $ref: '#/components/schemas/ArticleMetadata'
            - $ref: '#/components/schemas/SurveyMetadata'
          description: 課程內容元資料（依 lessonType 而異）
        orderIndex:
          type: integer
          description: 排序索引（用於課程排序）
          example: 1
        durationMinutes:
          type: integer
          description: 課程時長（分鐘）（可選）
          example: 45
        isFreePreview:
          type: boolean
          description: 是否為免費試看
          example: true
        isCompleted:
          type: boolean
          description: 是否已完成（需要認證才有此欄位）
          example: false
        createdAt:
          type: string
          format: date-time
          description: 建立時間
          example: "2024-12-01T00:00:00Z"

    VideoMetadata:
      type: object
      description: 影片類型課程的元資料
      properties:
        videoProvider:
          type: string
          description: 影片提供平台（如 youtube）
          example: "youtube"
        videoId:
          type: string
          description: 影片 ID
          example: "abc123"
        thumbnailUrl:
          type: string
          format: uri
          description: 縮圖 URL
          example: "https://img.youtube.com/vi/abc123/maxresdefault.jpg"
      example:
        videoProvider: "youtube"
        videoId: "dQw4w9WgXcQ"
        thumbnailUrl: "https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg"

    ArticleMetadata:
      type: object
      description: 文章類型課程的元資料
      properties:
        author:
          type: string
          description: 作者
          example: "張老師"
        publishedDate:
          type: string
          format: date
          description: 發布日期
          example: "2024-12-01"
        readingTime:
          type: integer
          description: 預估閱讀時間（分鐘）
          example: 10
      example:
        author: "張老師"
        publishedDate: "2024-12-01"
        readingTime: 10

    SurveyMetadata:
      type: object
      description: 測驗類型課程的元資料
      properties:
        questionsCount:
          type: integer
          description: 題目數量
          example: 10
        passingScore:
          type: integer
          description: 及格分數
          example: 70
        timeLimit:
          type: integer
          description: 時間限制（分鐘）
          example: 30
      example:
        questionsCount: 10
        passingScore: 70
        timeLimit: 30

    ErrorResponse:
      type: object
      required:
        - timestamp
        - status
        - error
        - message
        - path
      properties:
        timestamp:
          type: string
          format: date-time
          description: 錯誤發生時間
          example: "2025-12-08T10:30:00Z"
        status:
          type: integer
          description: HTTP 狀態碼
          example: 404
        error:
          type: string
          description: 錯誤類型
          example: "Not Found"
        message:
          type: string
          description: 錯誤訊息
          example: "Resource not found"
        path:
          type: string
          description: 請求路徑
          example: "/api/lessons/999"
