openapi: 3.0.0
info:
  title: WaterBallSA Video Progress API
  version: 1.0.0
  description: |
    WaterBallSA 線上學習平台 - 影片進度追蹤 (Video Progress) API 規格

    **認證說明**：所有端點需要 JWT Bearer token 認證
    **功能說明**：記錄使用者觀看影片的進度（播放時間、完成百分比等）
    **自動完成**：當 completionPercentage >= 90% 時，自動標記為已完成

servers:
  - url: http://localhost:8081/api
    description: 開發環境
  - url: https://api.waterballsa.com/api
    description: 正式環境

paths:
  /lessons/{lessonId}/progress:
    post:
      summary: 儲存或更新影片進度
      description: 記錄使用者觀看影片的進度（建立或更新）
      operationId: saveProgress
      tags:
        - Video Progress
      security:
        - BearerAuth: []
      parameters:
        - name: lessonId
          in: path
          description: 課程 ID
          required: true
          schema:
            type: integer
          example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SaveProgressRequest'
      responses:
        "200":
          description: 進度儲存成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideoProgressDto'
        "400":
          description: 請求格式錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "401":
          description: 未提供有效的 JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "404":
          description: 找不到該課程
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    get:
      summary: 取得影片進度
      description: 取得使用者在特定課程的影片觀看進度
      operationId: getProgress
      tags:
        - Video Progress
      security:
        - BearerAuth: []
      parameters:
        - name: lessonId
          in: path
          description: 課程 ID
          required: true
          schema:
            type: integer
          example: 1
      responses:
        "200":
          description: 成功取得進度資訊
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideoProgressDto'
        "404":
          description: 找不到該課程或尚無進度記錄
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "401":
          description: 未提供有效的 JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /lessons/chapters/{chapterId}/progress:
    get:
      summary: 取得章節所有課程的進度
      description: 取得使用者在特定章節中所有課程的影片觀看進度
      operationId: getChapterProgress
      tags:
        - Video Progress
      security:
        - BearerAuth: []
      parameters:
        - name: chapterId
          in: path
          description: 章節 ID
          required: true
          schema:
            type: integer
          example: 1
      responses:
        "200":
          description: 成功取得章節進度列表
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VideoProgressDto'
        "404":
          description: 找不到該章節
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "401":
          description: 未提供有效的 JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT access token（格式：Bearer {token}）

  schemas:
    SaveProgressRequest:
      type: object
      required:
        - currentTimeSeconds
        - durationSeconds
        - completionPercentage
        - isCompleted
      properties:
        currentTimeSeconds:
          type: number
          format: double
          description: 當前播放時間（秒）
          example: 120.5
          minimum: 0
        durationSeconds:
          type: number
          format: double
          description: 影片總時長（秒）
          example: 600.0
          minimum: 0
        completionPercentage:
          type: number
          format: double
          description: 完成百分比（0-100）
          example: 20.08
          minimum: 0
          maximum: 100
        isCompleted:
          type: boolean
          description: 是否已完成（通常在 completionPercentage >= 90 時為 true）
          example: false

    VideoProgressDto:
      type: object
      required:
        - id
        - userId
        - lessonId
        - currentTimeSeconds
        - durationSeconds
        - completionPercentage
        - isCompleted
        - completedAt
        - createdAt
        - updatedAt
      properties:
        id:
          type: integer
          description: 進度記錄 ID
          example: 1
        userId:
          type: integer
          description: 使用者 ID
          example: 1
        lessonId:
          type: integer
          description: 課程 ID
          example: 1
        currentTimeSeconds:
          type: number
          format: double
          description: 當前播放時間（秒）
          example: 120.5
        durationSeconds:
          type: number
          format: double
          description: 影片總時長（秒）
          example: 600.0
        completionPercentage:
          type: number
          format: double
          description: 完成百分比（0-100）
          example: 20.08
        isCompleted:
          type: boolean
          description: 是否已完成
          example: false
        completedAt:
          type: string
          format: date-time
          nullable: true
          description: 完成時間（未完成時為 null）
          example: null
        createdAt:
          type: string
          format: date-time
          description: 建立時間
          example: "2025-01-15T12:00:00Z"
        updatedAt:
          type: string
          format: date-time
          description: 最後更新時間
          example: "2025-01-15T12:30:00Z"

    ErrorResponse:
      type: object
      required:
        - timestamp
        - status
        - error
        - message
        - path
      properties:
        timestamp:
          type: string
          format: date-time
          description: 錯誤發生時間
          example: "2025-12-08T10:30:00Z"
        status:
          type: integer
          description: HTTP 狀態碼
          example: 404
        error:
          type: string
          description: 錯誤類型
          example: "Not Found"
        message:
          type: string
          description: 錯誤訊息
          example: "Resource not found"
        path:
          type: string
          description: 請求路徑
          example: "/api/lessons/999/progress"
        validationErrors:
          type: object
          additionalProperties:
            type: string
          description: 驗證錯誤詳情（可選）
          example:
            currentTimeSeconds: "必須大於或等於 0"
